# Generated by Django 5.1.2 on 2024-11-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEDIDOS',
            fields=[
                ('IdPedido', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NoOrden', models.CharField(max_length=10)),
                ('MeseroEncargado', models.CharField(max_length=80)),
                ('Platillo', models.CharField(max_length=50)),
                ('Bebida', models.CharField(max_length=50)),
                ('Postre', models.CharField(max_length=50)),
                ('HoraRegistro', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('IdUsuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NoEmpleado', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=80)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Contrasena', models.CharField(max_length=50)),
                ('FechaRegistro', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ALUMNO',
        ),
    ]
