# Generated by Django 5.1.2 on 2024-11-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_pedidos_usuario_delete_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Posicion',
            field=models.CharField(max_length=1),
            preserve_default=False
        ),
    ]
