# Generated by Django 5.1.2 on 2024-11-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_usuario_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Posicion',
            field=models.CharField(choices=[('C', 'Chef'), ('M', 'Mesero')], max_length=1),
        ),
    ]
