# Generated by Django 5.1.2 on 2024-11-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_alter_usuario_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='IdUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
