# Generated by Django 5.1.2 on 2024-11-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_alter_usuario_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='IdPedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
