# Generated by Django 5.1.2 on 2024-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_pedidos_mesa_alter_usuario_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='Estatus',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'Entregado')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
