# Generated by Django 5.1.2 on 2024-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_pedidos_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='Estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado')], max_length=10),
        ),
    ]
